# Generated by Django 3.0.7 on 2020-07-27 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('currency', models.CharField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14)),
                ('date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spendings.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spendings.Member')),
                ('settlement_with_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_with', to='spendings.Member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spendings.Room'),
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14)),
                ('date', models.DateTimeField(auto_now=True)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depts_from', to='spendings.Member')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depts_to', to='spendings.Member')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dept',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, from_member_id=django.db.models.expressions.F('to_member_id')), name='not_from_to_same_member'),
        ),
    ]
