# Generated by Django 3.1.2 on 2020-10-31 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("spendings", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="member",
            unique_together={("room", "user"), ("room", "name")},
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(
                check=models.Q(_negated=True, member_id=django.db.models.expressions.F("settlement_with_member_id")),
                name="not_with_same_member",
            ),
        ),
    ]
