# Generated by Django 3.0.7 on 2020-06-21 16:00

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0001_squashed_0003_auto_20200621_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], max_length=3),
        ),
        migrations.AlterField(
            model_name='spending',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
    ]
