# Generated by Django 3.0.7 on 2020-06-21 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spendings", "0002_auto_20200621_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spending",
            name="member",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="spendings.Member",),
        ),
    ]
